name: Native Full Build

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest
    container:
      image: rust:latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install additional components
      run: |
        rustup component add clippy
        apt-get update && apt-get install -y git

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run cargo check
      run: cargo check --all-targets --all-features

    - name: Build all libraries and binaries (debug)
      run: cargo build --all-targets --all-features

    - name: Build all libraries and binaries (release)
      run: cargo build --release --all-targets --all-features

    - name: Clean target directory (ensure it's not persisted)
      run: rm -rf target/
