name: Build Crash Upload Component in Native Environment

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-device-mgt-service-test/native-platform:latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust Toolchain components
      run: |
        if ! command -v cargo &> /dev/null; then
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
        fi
        rustup update stable
        rustup default stable

    - name: Add Rust to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install additional components
      run: rustup component add clippy

    - name: Run cargo check
      run: cargo check --all-targets --all-features

    - name: Run clippy (do not fail on warnings)
      run: cargo clippy --all-targets --all-features -- -D warnings || true

    - name: Build all libraries and binaries (debug)
      run: cargo build --all-targets --all-features

    - name: Build all libraries and binaries (release)
      run: cargo build --release --all-targets --all-features

    - name: Clean target directory (ensure it's not persisted)
      run: rm -rf target/
