name: Component Release

permissions:
  contents: write

on:
  pull_request: 
    types: [opened, edited, ready_for_review, closed]
    branches:
      - develop

jobs:
  validate-version:
    if: ${{ github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'ready_for_review' }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR description version field
        env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}
        run: |
          if ! echo "$PR_DESCRIPTION" | grep -qiE 'version[[:space:]]*:[[:space:]]*(major|minor|patch|none)'; then
            echo "[release.yml] ERROR: Pull Request description must include a version field in the format 'version: major|minor|patch|none' (case-insensitive)"
            exit 1
          fi
          echo "[release.yml] INFO: Validation passed: version field found."

  dispatch-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR version field
        id: version
        env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}
        run: |
          VERSION_TYPE=$(echo "$PR_DESCRIPTION" | grep -oiP 'version\s*:\s*\K(major|minor|patch|none)' | tr '[:upper:]' '[:lower:]')
          if [[ -z "$VERSION_TYPE" ]]; then
            echo "[release.yml] ERROR: No version data found in Pull Request description, defaulting to none."
            VERSION_TYPE="none"
          fi
          echo "version_type=$VERSION_TYPE" >> $GITHUB_OUTPUT
          echo "[release.yml] INFO: Detected version type: $VERSION_TYPE"

      - name: Dispatch release to Device Management Repo
        if: steps.version.outputs.version_type != 'none'
        env:
            VERSION_TYPE: ${{ steps.version.outputs.version_type }}
            COMPONENT_REPO: ${{ github.repository }}
        run: |
          payload=$(jq -n \
          --arg version_type "$VERSION_TYPE" \
          --arg component_repo "$COMPONENT_REPO" \
          '{ref: "main", inputs: {version_type: $version_type, component_repo: $component_repo}}')

          curl -X POST \
            -H "Authorization: token ${{ secrets.MGMT_REPO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ secrets.MGMT_REPO }}/actions/workflows/component-release.yml/dispatches \
            -d "$payload"
            echo "[release.yml] INFO: Dispatched release workflow to management repo with version type: $VERSION_TYPE"